import filter from "../filter";
import Problem from "../Problem";
import sum from "../sum";
import takeUntil from "../takeUntil";
import fibonacci from "../fibonacci";

export const Problem2: Problem = {
    number: 2,
    description: `Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.`,
    solve(): Promise<number> {
        return Promise.resolve(sum(
            takeUntil(
                filter(fibonacci(), (item: number): boolean => item % 2 === 0),
                (item: number): boolean => item > 4000000
            )
        ));
    }
};